<<<<<<< HEAD
uuid: 59b39102-d4ed-49c8-bdce-bc398fac7bfc
=======
uuid: 783b25eb-15d6-4178-91ae-7388ce0c9cd3
>>>>>>> f2cb6aef4afe6558d53bfe058c3848eba3b67d5e
langcode: en
status: true
dependencies:
  enforced:
    module:
      - devel
_core:
  default_config_hash: 3V-l1uuTcyirYOGLPZV5HWaDfr02uEbWZJIwc8Byz-c
id: devel
label: Development
description: 'Links related to Devel module.'
locked: true
